modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/ProjectEssentials/ProjectEssentials-Home/issues"

[[mods]]
    modId="project_essentials_home"
    version="1.14.4-1.1.0"
    displayName="Project Essentials Home"
    updateJSONURL="https://raw.githubusercontent.com/ProjectEssentials/ProjectEssentials-Home/MC-1.14.4/update.json"
    displayURL="https://github.com/ProjectEssentials/ProjectEssentials-Home"
    credits="Thanks JetBrains for Intellij IDEA license!"
    authors="MairwunNx (Pavel Erokhin)"
    description='''
    Project Essentials Home - additional module for Essentials;
    Just controlling player homies positions.
    '''

[[dependencies.projectessentialspermissions]]
    modId="project_essentials_core"
    mandatory=true
    versionRange="[1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.projectessentialsspawn]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.projectessentialsspawn]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
