modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/ProjectEssentials/ProjectEssentials-Home/issues"

[[mods]]
    modId="project_essentials_home"
    version="${file.jarVersion}"
    displayName="Project Essentials Home"
    updateJSONURL="https://raw.githubusercontent.com/ProjectEssentials/ProjectEssentials-Home/MC-1.15.2/updatev2.json"
    displayURL="https://github.com/ProjectEssentials/ProjectEssentials-Home"
    credits="hujle, JetBrains, all forge developers, and other contributors"
    authors="MairwunNx (Pavel Erokhin)"
    description='''
    A wonderful module not to lose your home! The module allows you to create,
    delete and teleport to homes.
    '''

[[dependencies.projectessentialspermissions]]
    modId="project_essentials_core"
    mandatory=true
    versionRange="[2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.projectessentialsspawn]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.projectessentialsspawn]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
